# Generated by Django 4.0.1 on 2023-11-06 17:42

from django.db import migrations, models
import fileuploadtron_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='storedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaderName', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=260)),
                ('fileData', models.FileField(upload_to='stored_files/')),
                ('fileSize', models.BigIntegerField(default=fileuploadtron_app.models.default_integer)),
                ('expirationDateTime', models.DateTimeField(default=fileuploadtron_app.models.default_expiration_date)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='custom_users', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_users_permissions', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
