# Generated by Django 4.0.1 on 2023-11-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedfile',
            name='uploaderName',
        ),
        migrations.AddField(
            model_name='storedfile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
