# Generated by Django 4.0.1 on 2023-11-09 16:49

from django.db import migrations, models
import fileuploadtron_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0002_remove_storedfile_uploadername_storedfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='uploadDateTime',
            field=models.DateTimeField(default=fileuploadtron_app.models.current_date),
        ),
    ]
