# Generated by Django 4.0.1 on 2023-11-09 21:38

from django.db import migrations, models
import django.db.models.deletion
import fileuploadtron_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0004_filecollection_storedfile_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='collection',
            field=models.ForeignKey(default=fileuploadtron_app.models.default_None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileuploadtron_app.filecollection'),
        ),
    ]
