# Generated by Django 4.0.1 on 2023-11-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0005_alter_storedfile_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedfile',
            name='collection',
        ),
        migrations.DeleteModel(
            name='FileCollection',
        ),
    ]
