# Generated by Django 4.0.1 on 2023-11-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0007_filecollection_storedfile_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecollection',
            name='hashed_password',
            field=models.CharField(default='pbkdf2_sha256$320000$qvlarKmrh9TPbseuorKt3k$3yc825WAuflUbW9hAgfPkZenVwA4ynfAHwaChymUCRQ=', max_length=128),
        ),
    ]
