# Generated by Django 4.0.1 on 2023-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0008_filecollection_hashed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecollection',
            name='hashed_password',
            field=models.CharField(default='pbkdf2_sha256$320000$Pnpq8A2mUPJZuzj4VUNZMp$EOJANm63uMj5yLWTJepxXFWIsj0X98oAhcodKOkNbas=', max_length=128),
        ),
    ]
