# Generated by Django 4.0.1 on 2023-11-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0009_alter_filecollection_hashed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_collections',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='fileuploadtron_app.FileCollection'),
        ),
        migrations.AlterField(
            model_name='filecollection',
            name='hashed_password',
            field=models.CharField(default='pbkdf2_sha256$320000$mVnmTs2HG4ApPDdljW1yBI$FRpKVgl4EdiC88B7VolCllFTTSWcAmQIcC0vBSe8WV0=', max_length=128),
        ),
    ]
