# Generated by Django 4.0.1 on 2023-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0010_customuser_favorite_collections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecollection',
            name='hashed_password',
            field=models.CharField(default='pbkdf2_sha256$320000$ptuNB6MSddZAcBiCLvV6qm$g0gLQib4fg+WXWk0zE7H2sIbK9trWbHhguX9qyqdJ9o=', max_length=128),
        ),
    ]
