# Generated by Django 4.0.1 on 2024-01-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0012_filecollection_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecollection',
            name='hashed_password',
            field=models.CharField(default='pbkdf2_sha256$320000$QZzfmufiWlhOlE421B6Ugk$vCz6SspUC6Rp1iGRKC+N/iYHhP1e3XjXbV6FKqjzCu4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='filecollection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
