# Generated by Django 4.0.1 on 2024-01-10 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtron_app', '0013_alter_filecollection_hashed_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='filecollection',
            name='hashed_password',
            field=models.CharField(default='pbkdf2_sha256$320000$b9uomgrXgkWAPvawvXxJKj$J3rg6jLfSj/RXLLDkoTnPPpys9sZ2cbxkEVBlDR/AWQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='filecollection',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
