# Generated by Django 4.0.1 on 2023-10-14 17:21

from django.db import migrations, models
import winrates_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=260)),
                ('file_data', models.FileField(upload_to='stored_files/')),
                ('expirationDateTime', models.DateTimeField(default=winrates_app.models.default_expiration_date)),
            ],
        ),
    ]
