# Generated by Django 4.0.1 on 2023-10-14 18:08

from django.db import migrations, models
import winrates_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('winrates_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedfile',
            old_name='file_data',
            new_name='fileData',
        ),
        migrations.RenameField(
            model_name='storedfile',
            old_name='uploader_name',
            new_name='uploaderName',
        ),
        migrations.AddField(
            model_name='storedfile',
            name='fileSize',
            field=models.BigIntegerField(default=winrates_app.models.default_integer),
        ),
    ]
